### ISSUE TITLE
Add example data

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/PiCam#2]

**Comment by serbinsh** [comment]
@Daryl-YANG is this complete?

**Comment by serbinsh** [comment]
@Daryl-YANG ping - do you consider this complete?

**Comment by Daryl-YANG** [comment]
The example data is completed. I just uploaded the GCC time series extraction code to your branch.

**Comment by serbinsh** [comment]
Example data now being organized over on OSF.io https://osf.io/k9xb3/
